### ISSUE TITLE
Cart detection

### ISSUE THREAD

**Issue by dikdom** [Idorobots/atari-xe-multicart#35]
Hello,
could you please describe how an Atari XL/XE detects if a cart is present in the system? I thought it triggers a low /S4 and checks if RD4 is high (and respectively triggers /S5 and checks RD5) but in this case the 373 provides random output after poweron, so it should not work... 👍  (but it does at your end).

Thanks!
Erm... RD5 is always set high, so I guess the machine triggers /S5 and RD5 is high -> cartridge is present.

**Comment by Idorobots** [comment]
Hi, indeed, whenever the cart is in the slot it'll register as present. The 373 goof up is known, surprisingly I had some good luck with TI parts always coming on in a known state, so I never noticed that originally. I don't have an Atari on hand these days, so I never bothered fixing the issue. :) A generally better idea would be to use a latch with master reset, as to ensure a proper state after startup.
