### ISSUE TITLE
How to generate the compiled bin to program?

### ISSUE THREAD

**Issue by repetto74** [Idorobots/atari-xe-multicart#37]
Hi,
I am struggling in trying to understand how to generate a compiled bin file with my rom selections and menu.
I am using Windows10 and try to use "make" command from the console but it does not work. I tried with buildcart.py and I get the message that no roms have been found despite 8k and 16k roms are copied in the roms folder.
Is there a more detailed guide on steps to perform here? What need to be installed?
Thanks
Rick

**Comment by Idorobots** [comment]
Hi, I don't currently have access to any windows machines, but if memory serves me right, there were pre-made unix-like development environments available for Windows. MinGW and Cygwin are two such examples, but there is also the newly added Windows Subsystem for Linux that should also support makefiles via an external program (see [here for more info]( https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows)).
Once you have either of those set up, it should be a matter of just placing your ROM files into the `roms` directory and then running the make command.

**Comment by repetto74** [comment]
Hi Idorobots,
Thank you for your reply :-). I will give a look to your link at try to figure out how to install a proper working environment to compile under Windows 10.
Have a good day!
Rick

**Comment by repetto74** [comment]
I have installed Make on Windows 10. When I try to compile I get this message from the CMD console:
```
C:\Users\RICCARDO REPETTO\Desktop\atari-xe-multicart-master>make clean && make
rm -f src/games.c
process_begin: CreateProcess(NULL, rm -f src/games.c, ...) failed.
make (e=2): Le fichier spécifié est introuvable. --file not found--
make: *** [clean] Error 2
```
What am I doing wrong here?

**Comment by Idorobots** [comment]
Yeah, that's my sloppy Makefile complaining that it can't clean the intermediate files, because they don't exist :) You can skip the `make clean` call and go directly to `make`. That should create the files and compile a binary blob for you to flash on the EEPROM.

**Comment by repetto74** [comment]
Unfortunately same with make command

```
C:\Users\RICCARDO REPETTO\Desktop\atari-xe-multicart-master>make
./buildcart.py --config --output src/games.c roms/*
process_begin: CreateProcess(NULL, env python3 C:\Users\RICCARDO REPETTO\Desktop\atari-xe-multicart-master\buildcart.py --config --output src/games.c roms/*, ...) failed.
make (e=2): Le fichier spécifié est introuvable.
make: *** [src/games.c] Erreur 2
```

**Comment by Idorobots** [comment]
Looks like the Python3 binary is missing. There's a little script that glues the ROMs together written in Python that runs during the build process. I think installing Python3 should fix that one. :)

**Comment by Idorobots** [comment]
Added all the dependencies that need to be set up to the README, next to python3, you'll need the [CC65](https://cc65.github.io/) compiler some other stuff.

**Comment by repetto74** [comment]
Thanks for the explanations :-)
I have installed already the CC65 and set-up the variable parameters to use it via the console prompt but maybe the path is not pointing to the folder for Atari XL source.
For Python3 it is weird because i have already a Python3.7 release installed on Windows10 unless I need to have only version 3.0.
Still continuing with some trials then :-)

**Comment by Idorobots** [comment]
Python 3.7 should be fine. Is it accessible from the environment you run Make from? If not, then probably the PATH variable (or whatever Windows is using for the same purpose) needs to be adjusted.

**Comment by repetto74** [comment]
You are totally right ! :-). Although I have Python 3.7 installed I did not set the path variable!
I will set it up and hopefully it should work now :-)
make, gcc and cc65 are already installed and set-up.

**Comment by repetto74** [comment]
Back again with bad news. Unfortunately I get the same error even after setting variable parameters for the Python executable. Is there any chance to have at least a testing bin that I can program to check if the multicart is working?

**Comment by Idorobots** [comment]
Hi, attached the menu.bin in a zip. It should be runnable on any emulator as a standalone cart, and it can be programmed on the multicart without any games. I think it'll still list some selection, but then it'll execute some garbage that is on the eeprom instead.

[menu.zip](https://github.com/Idorobots/atari-xe-multicart/files/9074546/menu.zip)

**Comment by repetto74** [comment]
Thanks, I will give it a try :-). And hope I can figure out how to set-up the environment to compile properly :-)

**Comment by repetto74** [comment]
Menu works on the emulator so I will confirm the multicart is ok on a real 800XL :-)

**Comment by repetto74** [comment]
Well it is a total fail for me :(. Programmed a 27c040 with the menu.bin and set the jumpers but all I get is a red screen at startup. Tried with a Winbond 27c020 + jumper settings but same result on screen.
Checked both 74HCT08 and 74HCT373 and they are reported good by the TL866 programmer. Checked continuity on jumpers and all is ok. 
Tried the 800XL with a genuine cartridge and working fine.
Bad luck here :-(.

**Comment by Idorobots** [comment]
Hmm, that's an oddly consistent thing to happen for a random garbage in the memory.  It should be possible to put any 8k ROM in the start of the eeprom and then the multicart should behave exactly like a regular 8k cart. Can you please see if that happens to work?

**Comment by repetto74** [comment]
Yes, I will burn any 8k game info the eprom and test it :-)
Keep you posted !

**Comment by repetto74** [comment]
Bad news again unfortunately :-(. I burned galaxian (8k) onto the eprom but still the same issue with just garbage color on screen.
I have tested the BS170 mosfet as being good between G,S and D. I am trying to narrow down possible hardware issues here and I can only think about 2 things:

- the 2 IC logics are rebranded ones(got them from Aliexpress) and could be LS instead of HTC (thus the programmer is checking both of them correctly). I do not know how much this can have an impact on the hardware.
- The socket of the 74HTC08 is maybe bad and gives intermittent connectivity (I do not like some of the pins and I will change it).
For the rest I really do not see where the issue may be.

![IMG_3699](https://user-images.githubusercontent.com/69641967/178153411-b5dad881-3e66-49f2-b55f-058e3514edec.JPG)
![IMG_3700](https://user-images.githubusercontent.com/69641967/178153412-3d27d136-555f-40ab-a632-78c1bb42caea.JPG)

**Comment by Idorobots** [comment]
Hmm, hard to tell what's going on in here. I no longer have a multicart or an Atari on hand to try to help you troubleshoot, but judging by the schematic it should be possible to only populate the EEPROM and the 7408 to get a dumb one game cartridge. There is a known problem with this design and some 74373 parts that produce a random garbage on the outputs when they power up which is messing up the menu startup. Perhaps that's what you're running into as well?
I never came across this problem back when I made this multicart design and I think I was using TI parts for mine.

**Comment by repetto74** [comment]
Indeed really a puzzling issue here.
Tried to remove the 74373 and same red screen.
I will replace the socket of the 74LS08 and also try the multicart on a spare 600Xl I have in order to check if it is not due to incompatibility with my 800XL. If no luck then I will put this cart aside and move to something else :-).

**Comment by Idorobots** [comment]
The only other thing I can think of is the EEPROM. Multicart accepts different JEDEC EEPROM sizes and there are jumpers there for the VCC supply pin. I assume your chip is conformant to the JEDEC pinout and is getting the VCC and GND connections. Perhaps you set up the other address pins high via the jumpers and now it's executing something from the EEPROM, but not on the 0 address?

**Comment by repetto74** [comment]
How can I make sure the eprom is JEDEC compliant? It is branded AM27C040 and programs as expected with programmer settings to AM27C040. I have tried also a Winbond 27C020 with same result. Jumpers are set on the board as per the instructions so I assume this is ok.
27c040 - J1 UP, J2 DOWN, J3 DOWN, J4 DOWN

**Comment by Idorobots** [comment]
According to its datasheet it is compliant, the jumper settings are also correct. Short of hooking up a logic analyzer and checking what's going on directly on the cart bus, I'm out of ideas at this point. :(

**Comment by repetto74** [comment]
Let me replace the socket of the 74LS08 to be on the safe side. I will then try to troubleshoot further :-)
Thanks for you help!

**Comment by repetto74** [comment]
Just to close this topic. 
I have replaced the suspicious socket but still multicart not working :-(. 
It can be any as maybe just a faulty PCB manufacture but to much assle. I will move to the Unocart  and have it built as soon as I'll get PCBs and components :-)

**Comment by Idorobots** [comment]
I'm sad to hear. :( Good luck with the Unocart!
